#!/bin/sh

fail () {
  echo $1 >&2
  exit 0
}

retry () {
  local n=1
  local max=20
  local delay=10
  while true; do
    "$@" && break || {
      if [[ $n -lt $max ]]; then
        ((n++))
        echo "Command failed. Attempt $n/$max:"
        sleep $delay;
      else
        fail "The command has failed after $n attempts."
      fi
    }
  done
}

# source: https://unix.stackexchange.com/a/137639

retry cp /var/vcap/packages/sudo-1.9.5p2/bin/sudo /usr/bin/sudo
